################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../UCGUI/Widget/BUTTON.c \
../UCGUI/Widget/BUTTON_BMP.c \
../UCGUI/Widget/BUTTON_Bitmap.c \
../UCGUI/Widget/BUTTON_Create.c \
../UCGUI/Widget/BUTTON_CreateIndirect.c \
../UCGUI/Widget/BUTTON_Default.c \
../UCGUI/Widget/BUTTON_Get.c \
../UCGUI/Widget/BUTTON_GetBitmap.c \
../UCGUI/Widget/BUTTON_IsPressed.c \
../UCGUI/Widget/BUTTON_SelfDraw.c \
../UCGUI/Widget/BUTTON_SetFocusColor.c \
../UCGUI/Widget/BUTTON_SetTextAlign.c \
../UCGUI/Widget/BUTTON_StreamedBitmap.c \
../UCGUI/Widget/BUTTON__SetBitmapObj.c \
../UCGUI/Widget/CHECKBOX.c \
../UCGUI/Widget/CHECKBOX_Create.c \
../UCGUI/Widget/CHECKBOX_CreateIndirect.c \
../UCGUI/Widget/CHECKBOX_Default.c \
../UCGUI/Widget/CHECKBOX_GetState.c \
../UCGUI/Widget/CHECKBOX_GetText.c \
../UCGUI/Widget/CHECKBOX_Image.c \
../UCGUI/Widget/CHECKBOX_IsChecked.c \
../UCGUI/Widget/CHECKBOX_SetBkColor.c \
../UCGUI/Widget/CHECKBOX_SetBoxBkColor.c \
../UCGUI/Widget/CHECKBOX_SetDefaultImage.c \
../UCGUI/Widget/CHECKBOX_SetFocusColor.c \
../UCGUI/Widget/CHECKBOX_SetFont.c \
../UCGUI/Widget/CHECKBOX_SetImage.c \
../UCGUI/Widget/CHECKBOX_SetNumStates.c \
../UCGUI/Widget/CHECKBOX_SetSpacing.c \
../UCGUI/Widget/CHECKBOX_SetState.c \
../UCGUI/Widget/CHECKBOX_SetText.c \
../UCGUI/Widget/CHECKBOX_SetTextAlign.c \
../UCGUI/Widget/CHECKBOX_SetTextColor.c \
../UCGUI/Widget/DIALOG.c \
../UCGUI/Widget/DROPDOWN.c \
../UCGUI/Widget/DROPDOWN_AddString.c \
../UCGUI/Widget/DROPDOWN_Create.c \
../UCGUI/Widget/DROPDOWN_CreateIndirect.c \
../UCGUI/Widget/DROPDOWN_Default.c \
../UCGUI/Widget/DROPDOWN_DeleteItem.c \
../UCGUI/Widget/DROPDOWN_GetNumItems.c \
../UCGUI/Widget/DROPDOWN_InsertString.c \
../UCGUI/Widget/DROPDOWN_ItemSpacing.c \
../UCGUI/Widget/DROPDOWN_SetAutoScroll.c \
../UCGUI/Widget/DROPDOWN_SetBkColor.c \
../UCGUI/Widget/DROPDOWN_SetColor.c \
../UCGUI/Widget/DROPDOWN_SetFont.c \
../UCGUI/Widget/DROPDOWN_SetScrollbarColor.c \
../UCGUI/Widget/DROPDOWN_SetScrollbarWidth.c \
../UCGUI/Widget/DROPDOWN_SetTextAlign.c \
../UCGUI/Widget/DROPDOWN_SetTextColor.c \
../UCGUI/Widget/DROPDOWN_SetTextHeight.c \
../UCGUI/Widget/EDIT.c \
../UCGUI/Widget/EDITBin.c \
../UCGUI/Widget/EDITDec.c \
../UCGUI/Widget/EDITFloat.c \
../UCGUI/Widget/EDITHex.c \
../UCGUI/Widget/EDITUlong.c \
../UCGUI/Widget/EDIT_Create.c \
../UCGUI/Widget/EDIT_CreateIndirect.c \
../UCGUI/Widget/EDIT_Default.c \
../UCGUI/Widget/EDIT_GetCursorPixelPos.c \
../UCGUI/Widget/EDIT_GetCursorPos.c \
../UCGUI/Widget/EDIT_GetNumChars.c \
../UCGUI/Widget/EDIT_SetCursorAtChar.c \
../UCGUI/Widget/EDIT_SetFocussable.c \
../UCGUI/Widget/EDIT_SetInsertMode.c \
../UCGUI/Widget/EDIT_SetSel.c \
../UCGUI/Widget/EDIT_SetTextMode.c \
../UCGUI/Widget/EDIT_SetpfAddKeyEx.c \
../UCGUI/Widget/EDIT_SetpfUpdateBuffer.c \
../UCGUI/Widget/FRAMEWIN.c \
../UCGUI/Widget/FRAMEWIN_AddMenu.c \
../UCGUI/Widget/FRAMEWIN_Button.c \
../UCGUI/Widget/FRAMEWIN_ButtonClose.c \
../UCGUI/Widget/FRAMEWIN_ButtonMax.c \
../UCGUI/Widget/FRAMEWIN_ButtonMin.c \
../UCGUI/Widget/FRAMEWIN_Create.c \
../UCGUI/Widget/FRAMEWIN_CreateIndirect.c \
../UCGUI/Widget/FRAMEWIN_Default.c \
../UCGUI/Widget/FRAMEWIN_Get.c \
../UCGUI/Widget/FRAMEWIN_IsMinMax.c \
../UCGUI/Widget/FRAMEWIN_MinMaxRest.c \
../UCGUI/Widget/FRAMEWIN_SetBorderSize.c \
../UCGUI/Widget/FRAMEWIN_SetColors.c \
../UCGUI/Widget/FRAMEWIN_SetFont.c \
../UCGUI/Widget/FRAMEWIN_SetResizeable.c \
../UCGUI/Widget/FRAMEWIN_SetTitleHeight.c \
../UCGUI/Widget/FRAMEWIN_SetTitleVis.c \
../UCGUI/Widget/FRAMEWIN__UpdateButtons.c \
../UCGUI/Widget/GRAPH.c \
../UCGUI/Widget/GRAPH_CreateIndirect.c \
../UCGUI/Widget/GRAPH_DATA_XY.c \
../UCGUI/Widget/GRAPH_DATA_YT.c \
../UCGUI/Widget/GRAPH_SCALE.c \
../UCGUI/Widget/GUI_ARRAY.c \
../UCGUI/Widget/GUI_ARRAY_DeleteItem.c \
../UCGUI/Widget/GUI_ARRAY_InsertItem.c \
../UCGUI/Widget/GUI_ARRAY_ResizeItem.c \
../UCGUI/Widget/GUI_DRAW.c \
../UCGUI/Widget/GUI_DRAW_BITMAP.c \
../UCGUI/Widget/GUI_DRAW_BMP.c \
../UCGUI/Widget/GUI_DRAW_STREAMED.c \
../UCGUI/Widget/GUI_DRAW_Self.c \
../UCGUI/Widget/GUI_EditBin.c \
../UCGUI/Widget/GUI_EditDec.c \
../UCGUI/Widget/GUI_EditFloat.c \
../UCGUI/Widget/GUI_EditHex.c \
../UCGUI/Widget/GUI_EditString.c \
../UCGUI/Widget/GUI_HOOK.c \
../UCGUI/Widget/HEADER.c \
../UCGUI/Widget/HEADER_BMP.c \
../UCGUI/Widget/HEADER_Bitmap.c \
../UCGUI/Widget/HEADER_Create.c \
../UCGUI/Widget/HEADER_CreateIndirect.c \
../UCGUI/Widget/HEADER_GetSel.c \
../UCGUI/Widget/HEADER_SetDragLimit.c \
../UCGUI/Widget/HEADER_StreamedBitmap.c \
../UCGUI/Widget/HEADER__SetDrawObj.c \
../UCGUI/Widget/LISTBOX.c \
../UCGUI/Widget/LISTBOX_Create.c \
../UCGUI/Widget/LISTBOX_CreateIndirect.c \
../UCGUI/Widget/LISTBOX_Default.c \
../UCGUI/Widget/LISTBOX_DeleteItem.c \
../UCGUI/Widget/LISTBOX_Font.c \
../UCGUI/Widget/LISTBOX_GetItemText.c \
../UCGUI/Widget/LISTBOX_GetNumItems.c \
../UCGUI/Widget/LISTBOX_GetTextAlign.c \
../UCGUI/Widget/LISTBOX_InsertString.c \
../UCGUI/Widget/LISTBOX_ItemDisabled.c \
../UCGUI/Widget/LISTBOX_ItemSpacing.c \
../UCGUI/Widget/LISTBOX_MultiSel.c \
../UCGUI/Widget/LISTBOX_ScrollStep.c \
../UCGUI/Widget/LISTBOX_SetAutoScroll.c \
../UCGUI/Widget/LISTBOX_SetBkColor.c \
../UCGUI/Widget/LISTBOX_SetOwner.c \
../UCGUI/Widget/LISTBOX_SetOwnerDraw.c \
../UCGUI/Widget/LISTBOX_SetScrollbarColor.c \
../UCGUI/Widget/LISTBOX_SetScrollbarWidth.c \
../UCGUI/Widget/LISTBOX_SetString.c \
../UCGUI/Widget/LISTBOX_SetTextAlign.c \
../UCGUI/Widget/LISTBOX_SetTextColor.c \
../UCGUI/Widget/LISTVIEW.c \
../UCGUI/Widget/LISTVIEW_Create.c \
../UCGUI/Widget/LISTVIEW_CreateIndirect.c \
../UCGUI/Widget/LISTVIEW_Default.c \
../UCGUI/Widget/LISTVIEW_DeleteAllRows.c \
../UCGUI/Widget/LISTVIEW_DeleteColumn.c \
../UCGUI/Widget/LISTVIEW_DeleteRow.c \
../UCGUI/Widget/LISTVIEW_DisableRow.c \
../UCGUI/Widget/LISTVIEW_GetBkColor.c \
../UCGUI/Widget/LISTVIEW_GetFont.c \
../UCGUI/Widget/LISTVIEW_GetHeader.c \
../UCGUI/Widget/LISTVIEW_GetItemText.c \
../UCGUI/Widget/LISTVIEW_GetNumColumns.c \
../UCGUI/Widget/LISTVIEW_GetNumRows.c \
../UCGUI/Widget/LISTVIEW_GetSel.c \
../UCGUI/Widget/LISTVIEW_GetTextColor.c \
../UCGUI/Widget/LISTVIEW_InsertRow.c \
../UCGUI/Widget/LISTVIEW_SetAutoScroll.c \
../UCGUI/Widget/LISTVIEW_SetBkColor.c \
../UCGUI/Widget/LISTVIEW_SetColumnWidth.c \
../UCGUI/Widget/LISTVIEW_SetFont.c \
../UCGUI/Widget/LISTVIEW_SetGridVis.c \
../UCGUI/Widget/LISTVIEW_SetItemColor.c \
../UCGUI/Widget/LISTVIEW_SetItemText.c \
../UCGUI/Widget/LISTVIEW_SetLBorder.c \
../UCGUI/Widget/LISTVIEW_SetRBorder.c \
../UCGUI/Widget/LISTVIEW_SetRowHeight.c \
../UCGUI/Widget/LISTVIEW_SetSel.c \
../UCGUI/Widget/LISTVIEW_SetSort.c \
../UCGUI/Widget/LISTVIEW_SetTextAlign.c \
../UCGUI/Widget/LISTVIEW_SetTextColor.c \
../UCGUI/Widget/LISTVIEW_UserData.c \
../UCGUI/Widget/MENU.c \
../UCGUI/Widget/MENU_Attach.c \
../UCGUI/Widget/MENU_CreateIndirect.c \
../UCGUI/Widget/MENU_Default.c \
../UCGUI/Widget/MENU_DeleteItem.c \
../UCGUI/Widget/MENU_DisableItem.c \
../UCGUI/Widget/MENU_EnableItem.c \
../UCGUI/Widget/MENU_GetItem.c \
../UCGUI/Widget/MENU_GetItemText.c \
../UCGUI/Widget/MENU_GetNumItems.c \
../UCGUI/Widget/MENU_InsertItem.c \
../UCGUI/Widget/MENU_Popup.c \
../UCGUI/Widget/MENU_SetBkColor.c \
../UCGUI/Widget/MENU_SetBorderSize.c \
../UCGUI/Widget/MENU_SetFont.c \
../UCGUI/Widget/MENU_SetItem.c \
../UCGUI/Widget/MENU_SetTextColor.c \
../UCGUI/Widget/MENU__FindItem.c \
../UCGUI/Widget/MESSAGEBOX.c \
../UCGUI/Widget/MULTIEDIT.c \
../UCGUI/Widget/MULTIEDIT_Create.c \
../UCGUI/Widget/MULTIEDIT_CreateIndirect.c \
../UCGUI/Widget/MULTIPAGE.c \
../UCGUI/Widget/MULTIPAGE_Create.c \
../UCGUI/Widget/MULTIPAGE_CreateIndirect.c \
../UCGUI/Widget/MULTIPAGE_Default.c \
../UCGUI/Widget/PROGBAR.c \
../UCGUI/Widget/PROGBAR_Create.c \
../UCGUI/Widget/PROGBAR_CreateIndirect.c \
../UCGUI/Widget/PROGBAR_SetBarColor.c \
../UCGUI/Widget/PROGBAR_SetFont.c \
../UCGUI/Widget/PROGBAR_SetMinMax.c \
../UCGUI/Widget/PROGBAR_SetText.c \
../UCGUI/Widget/PROGBAR_SetTextAlign.c \
../UCGUI/Widget/PROGBAR_SetTextColor.c \
../UCGUI/Widget/PROGBAR_SetTextPos.c \
../UCGUI/Widget/RADIO.c \
../UCGUI/Widget/RADIO_Create.c \
../UCGUI/Widget/RADIO_CreateIndirect.c \
../UCGUI/Widget/RADIO_Default.c \
../UCGUI/Widget/RADIO_GetText.c \
../UCGUI/Widget/RADIO_Image.c \
../UCGUI/Widget/RADIO_SetBkColor.c \
../UCGUI/Widget/RADIO_SetDefaultImage.c \
../UCGUI/Widget/RADIO_SetFocusColor.c \
../UCGUI/Widget/RADIO_SetFont.c \
../UCGUI/Widget/RADIO_SetGroupId.c \
../UCGUI/Widget/RADIO_SetImage.c \
../UCGUI/Widget/RADIO_SetText.c \
../UCGUI/Widget/RADIO_SetTextColor.c \
../UCGUI/Widget/SCROLLBAR.c \
../UCGUI/Widget/SCROLLBAR_Create.c \
../UCGUI/Widget/SCROLLBAR_CreateIndirect.c \
../UCGUI/Widget/SCROLLBAR_Defaults.c \
../UCGUI/Widget/SCROLLBAR_GetValue.c \
../UCGUI/Widget/SCROLLBAR_SetColor.c \
../UCGUI/Widget/SCROLLBAR_SetWidth.c \
../UCGUI/Widget/SLIDER.c \
../UCGUI/Widget/SLIDER_Create.c \
../UCGUI/Widget/SLIDER_CreateIndirect.c \
../UCGUI/Widget/SLIDER_Default.c \
../UCGUI/Widget/SLIDER_SetFocusColor.c \
../UCGUI/Widget/TEXT.c \
../UCGUI/Widget/TEXT_Create.c \
../UCGUI/Widget/TEXT_CreateIndirect.c \
../UCGUI/Widget/TEXT_Default.c \
../UCGUI/Widget/TEXT_SetBkColor.c \
../UCGUI/Widget/TEXT_SetFont.c \
../UCGUI/Widget/TEXT_SetText.c \
../UCGUI/Widget/TEXT_SetTextAlign.c \
../UCGUI/Widget/TEXT_SetTextColor.c \
../UCGUI/Widget/TEXT_SetWrapMode.c \
../UCGUI/Widget/WIDGET.c \
../UCGUI/Widget/WIDGET_Effect_3D.c \
../UCGUI/Widget/WIDGET_Effect_3D1L.c \
../UCGUI/Widget/WIDGET_Effect_3D2L.c \
../UCGUI/Widget/WIDGET_Effect_None.c \
../UCGUI/Widget/WIDGET_Effect_Simple.c \
../UCGUI/Widget/WIDGET_FillStringInRect.c \
../UCGUI/Widget/WIDGET_SetEffect.c \
../UCGUI/Widget/WIDGET_SetWidth.c \
../UCGUI/Widget/WINDOW.c \
../UCGUI/Widget/WINDOW_Default.c 

OBJS += \
./UCGUI/Widget/BUTTON.o \
./UCGUI/Widget/BUTTON_BMP.o \
./UCGUI/Widget/BUTTON_Bitmap.o \
./UCGUI/Widget/BUTTON_Create.o \
./UCGUI/Widget/BUTTON_CreateIndirect.o \
./UCGUI/Widget/BUTTON_Default.o \
./UCGUI/Widget/BUTTON_Get.o \
./UCGUI/Widget/BUTTON_GetBitmap.o \
./UCGUI/Widget/BUTTON_IsPressed.o \
./UCGUI/Widget/BUTTON_SelfDraw.o \
./UCGUI/Widget/BUTTON_SetFocusColor.o \
./UCGUI/Widget/BUTTON_SetTextAlign.o \
./UCGUI/Widget/BUTTON_StreamedBitmap.o \
./UCGUI/Widget/BUTTON__SetBitmapObj.o \
./UCGUI/Widget/CHECKBOX.o \
./UCGUI/Widget/CHECKBOX_Create.o \
./UCGUI/Widget/CHECKBOX_CreateIndirect.o \
./UCGUI/Widget/CHECKBOX_Default.o \
./UCGUI/Widget/CHECKBOX_GetState.o \
./UCGUI/Widget/CHECKBOX_GetText.o \
./UCGUI/Widget/CHECKBOX_Image.o \
./UCGUI/Widget/CHECKBOX_IsChecked.o \
./UCGUI/Widget/CHECKBOX_SetBkColor.o \
./UCGUI/Widget/CHECKBOX_SetBoxBkColor.o \
./UCGUI/Widget/CHECKBOX_SetDefaultImage.o \
./UCGUI/Widget/CHECKBOX_SetFocusColor.o \
./UCGUI/Widget/CHECKBOX_SetFont.o \
./UCGUI/Widget/CHECKBOX_SetImage.o \
./UCGUI/Widget/CHECKBOX_SetNumStates.o \
./UCGUI/Widget/CHECKBOX_SetSpacing.o \
./UCGUI/Widget/CHECKBOX_SetState.o \
./UCGUI/Widget/CHECKBOX_SetText.o \
./UCGUI/Widget/CHECKBOX_SetTextAlign.o \
./UCGUI/Widget/CHECKBOX_SetTextColor.o \
./UCGUI/Widget/DIALOG.o \
./UCGUI/Widget/DROPDOWN.o \
./UCGUI/Widget/DROPDOWN_AddString.o \
./UCGUI/Widget/DROPDOWN_Create.o \
./UCGUI/Widget/DROPDOWN_CreateIndirect.o \
./UCGUI/Widget/DROPDOWN_Default.o \
./UCGUI/Widget/DROPDOWN_DeleteItem.o \
./UCGUI/Widget/DROPDOWN_GetNumItems.o \
./UCGUI/Widget/DROPDOWN_InsertString.o \
./UCGUI/Widget/DROPDOWN_ItemSpacing.o \
./UCGUI/Widget/DROPDOWN_SetAutoScroll.o \
./UCGUI/Widget/DROPDOWN_SetBkColor.o \
./UCGUI/Widget/DROPDOWN_SetColor.o \
./UCGUI/Widget/DROPDOWN_SetFont.o \
./UCGUI/Widget/DROPDOWN_SetScrollbarColor.o \
./UCGUI/Widget/DROPDOWN_SetScrollbarWidth.o \
./UCGUI/Widget/DROPDOWN_SetTextAlign.o \
./UCGUI/Widget/DROPDOWN_SetTextColor.o \
./UCGUI/Widget/DROPDOWN_SetTextHeight.o \
./UCGUI/Widget/EDIT.o \
./UCGUI/Widget/EDITBin.o \
./UCGUI/Widget/EDITDec.o \
./UCGUI/Widget/EDITFloat.o \
./UCGUI/Widget/EDITHex.o \
./UCGUI/Widget/EDITUlong.o \
./UCGUI/Widget/EDIT_Create.o \
./UCGUI/Widget/EDIT_CreateIndirect.o \
./UCGUI/Widget/EDIT_Default.o \
./UCGUI/Widget/EDIT_GetCursorPixelPos.o \
./UCGUI/Widget/EDIT_GetCursorPos.o \
./UCGUI/Widget/EDIT_GetNumChars.o \
./UCGUI/Widget/EDIT_SetCursorAtChar.o \
./UCGUI/Widget/EDIT_SetFocussable.o \
./UCGUI/Widget/EDIT_SetInsertMode.o \
./UCGUI/Widget/EDIT_SetSel.o \
./UCGUI/Widget/EDIT_SetTextMode.o \
./UCGUI/Widget/EDIT_SetpfAddKeyEx.o \
./UCGUI/Widget/EDIT_SetpfUpdateBuffer.o \
./UCGUI/Widget/FRAMEWIN.o \
./UCGUI/Widget/FRAMEWIN_AddMenu.o \
./UCGUI/Widget/FRAMEWIN_Button.o \
./UCGUI/Widget/FRAMEWIN_ButtonClose.o \
./UCGUI/Widget/FRAMEWIN_ButtonMax.o \
./UCGUI/Widget/FRAMEWIN_ButtonMin.o \
./UCGUI/Widget/FRAMEWIN_Create.o \
./UCGUI/Widget/FRAMEWIN_CreateIndirect.o \
./UCGUI/Widget/FRAMEWIN_Default.o \
./UCGUI/Widget/FRAMEWIN_Get.o \
./UCGUI/Widget/FRAMEWIN_IsMinMax.o \
./UCGUI/Widget/FRAMEWIN_MinMaxRest.o \
./UCGUI/Widget/FRAMEWIN_SetBorderSize.o \
./UCGUI/Widget/FRAMEWIN_SetColors.o \
./UCGUI/Widget/FRAMEWIN_SetFont.o \
./UCGUI/Widget/FRAMEWIN_SetResizeable.o \
./UCGUI/Widget/FRAMEWIN_SetTitleHeight.o \
./UCGUI/Widget/FRAMEWIN_SetTitleVis.o \
./UCGUI/Widget/FRAMEWIN__UpdateButtons.o \
./UCGUI/Widget/GRAPH.o \
./UCGUI/Widget/GRAPH_CreateIndirect.o \
./UCGUI/Widget/GRAPH_DATA_XY.o \
./UCGUI/Widget/GRAPH_DATA_YT.o \
./UCGUI/Widget/GRAPH_SCALE.o \
./UCGUI/Widget/GUI_ARRAY.o \
./UCGUI/Widget/GUI_ARRAY_DeleteItem.o \
./UCGUI/Widget/GUI_ARRAY_InsertItem.o \
./UCGUI/Widget/GUI_ARRAY_ResizeItem.o \
./UCGUI/Widget/GUI_DRAW.o \
./UCGUI/Widget/GUI_DRAW_BITMAP.o \
./UCGUI/Widget/GUI_DRAW_BMP.o \
./UCGUI/Widget/GUI_DRAW_STREAMED.o \
./UCGUI/Widget/GUI_DRAW_Self.o \
./UCGUI/Widget/GUI_EditBin.o \
./UCGUI/Widget/GUI_EditDec.o \
./UCGUI/Widget/GUI_EditFloat.o \
./UCGUI/Widget/GUI_EditHex.o \
./UCGUI/Widget/GUI_EditString.o \
./UCGUI/Widget/GUI_HOOK.o \
./UCGUI/Widget/HEADER.o \
./UCGUI/Widget/HEADER_BMP.o \
./UCGUI/Widget/HEADER_Bitmap.o \
./UCGUI/Widget/HEADER_Create.o \
./UCGUI/Widget/HEADER_CreateIndirect.o \
./UCGUI/Widget/HEADER_GetSel.o \
./UCGUI/Widget/HEADER_SetDragLimit.o \
./UCGUI/Widget/HEADER_StreamedBitmap.o \
./UCGUI/Widget/HEADER__SetDrawObj.o \
./UCGUI/Widget/LISTBOX.o \
./UCGUI/Widget/LISTBOX_Create.o \
./UCGUI/Widget/LISTBOX_CreateIndirect.o \
./UCGUI/Widget/LISTBOX_Default.o \
./UCGUI/Widget/LISTBOX_DeleteItem.o \
./UCGUI/Widget/LISTBOX_Font.o \
./UCGUI/Widget/LISTBOX_GetItemText.o \
./UCGUI/Widget/LISTBOX_GetNumItems.o \
./UCGUI/Widget/LISTBOX_GetTextAlign.o \
./UCGUI/Widget/LISTBOX_InsertString.o \
./UCGUI/Widget/LISTBOX_ItemDisabled.o \
./UCGUI/Widget/LISTBOX_ItemSpacing.o \
./UCGUI/Widget/LISTBOX_MultiSel.o \
./UCGUI/Widget/LISTBOX_ScrollStep.o \
./UCGUI/Widget/LISTBOX_SetAutoScroll.o \
./UCGUI/Widget/LISTBOX_SetBkColor.o \
./UCGUI/Widget/LISTBOX_SetOwner.o \
./UCGUI/Widget/LISTBOX_SetOwnerDraw.o \
./UCGUI/Widget/LISTBOX_SetScrollbarColor.o \
./UCGUI/Widget/LISTBOX_SetScrollbarWidth.o \
./UCGUI/Widget/LISTBOX_SetString.o \
./UCGUI/Widget/LISTBOX_SetTextAlign.o \
./UCGUI/Widget/LISTBOX_SetTextColor.o \
./UCGUI/Widget/LISTVIEW.o \
./UCGUI/Widget/LISTVIEW_Create.o \
./UCGUI/Widget/LISTVIEW_CreateIndirect.o \
./UCGUI/Widget/LISTVIEW_Default.o \
./UCGUI/Widget/LISTVIEW_DeleteAllRows.o \
./UCGUI/Widget/LISTVIEW_DeleteColumn.o \
./UCGUI/Widget/LISTVIEW_DeleteRow.o \
./UCGUI/Widget/LISTVIEW_DisableRow.o \
./UCGUI/Widget/LISTVIEW_GetBkColor.o \
./UCGUI/Widget/LISTVIEW_GetFont.o \
./UCGUI/Widget/LISTVIEW_GetHeader.o \
./UCGUI/Widget/LISTVIEW_GetItemText.o \
./UCGUI/Widget/LISTVIEW_GetNumColumns.o \
./UCGUI/Widget/LISTVIEW_GetNumRows.o \
./UCGUI/Widget/LISTVIEW_GetSel.o \
./UCGUI/Widget/LISTVIEW_GetTextColor.o \
./UCGUI/Widget/LISTVIEW_InsertRow.o \
./UCGUI/Widget/LISTVIEW_SetAutoScroll.o \
./UCGUI/Widget/LISTVIEW_SetBkColor.o \
./UCGUI/Widget/LISTVIEW_SetColumnWidth.o \
./UCGUI/Widget/LISTVIEW_SetFont.o \
./UCGUI/Widget/LISTVIEW_SetGridVis.o \
./UCGUI/Widget/LISTVIEW_SetItemColor.o \
./UCGUI/Widget/LISTVIEW_SetItemText.o \
./UCGUI/Widget/LISTVIEW_SetLBorder.o \
./UCGUI/Widget/LISTVIEW_SetRBorder.o \
./UCGUI/Widget/LISTVIEW_SetRowHeight.o \
./UCGUI/Widget/LISTVIEW_SetSel.o \
./UCGUI/Widget/LISTVIEW_SetSort.o \
./UCGUI/Widget/LISTVIEW_SetTextAlign.o \
./UCGUI/Widget/LISTVIEW_SetTextColor.o \
./UCGUI/Widget/LISTVIEW_UserData.o \
./UCGUI/Widget/MENU.o \
./UCGUI/Widget/MENU_Attach.o \
./UCGUI/Widget/MENU_CreateIndirect.o \
./UCGUI/Widget/MENU_Default.o \
./UCGUI/Widget/MENU_DeleteItem.o \
./UCGUI/Widget/MENU_DisableItem.o \
./UCGUI/Widget/MENU_EnableItem.o \
./UCGUI/Widget/MENU_GetItem.o \
./UCGUI/Widget/MENU_GetItemText.o \
./UCGUI/Widget/MENU_GetNumItems.o \
./UCGUI/Widget/MENU_InsertItem.o \
./UCGUI/Widget/MENU_Popup.o \
./UCGUI/Widget/MENU_SetBkColor.o \
./UCGUI/Widget/MENU_SetBorderSize.o \
./UCGUI/Widget/MENU_SetFont.o \
./UCGUI/Widget/MENU_SetItem.o \
./UCGUI/Widget/MENU_SetTextColor.o \
./UCGUI/Widget/MENU__FindItem.o \
./UCGUI/Widget/MESSAGEBOX.o \
./UCGUI/Widget/MULTIEDIT.o \
./UCGUI/Widget/MULTIEDIT_Create.o \
./UCGUI/Widget/MULTIEDIT_CreateIndirect.o \
./UCGUI/Widget/MULTIPAGE.o \
./UCGUI/Widget/MULTIPAGE_Create.o \
./UCGUI/Widget/MULTIPAGE_CreateIndirect.o \
./UCGUI/Widget/MULTIPAGE_Default.o \
./UCGUI/Widget/PROGBAR.o \
./UCGUI/Widget/PROGBAR_Create.o \
./UCGUI/Widget/PROGBAR_CreateIndirect.o \
./UCGUI/Widget/PROGBAR_SetBarColor.o \
./UCGUI/Widget/PROGBAR_SetFont.o \
./UCGUI/Widget/PROGBAR_SetMinMax.o \
./UCGUI/Widget/PROGBAR_SetText.o \
./UCGUI/Widget/PROGBAR_SetTextAlign.o \
./UCGUI/Widget/PROGBAR_SetTextColor.o \
./UCGUI/Widget/PROGBAR_SetTextPos.o \
./UCGUI/Widget/RADIO.o \
./UCGUI/Widget/RADIO_Create.o \
./UCGUI/Widget/RADIO_CreateIndirect.o \
./UCGUI/Widget/RADIO_Default.o \
./UCGUI/Widget/RADIO_GetText.o \
./UCGUI/Widget/RADIO_Image.o \
./UCGUI/Widget/RADIO_SetBkColor.o \
./UCGUI/Widget/RADIO_SetDefaultImage.o \
./UCGUI/Widget/RADIO_SetFocusColor.o \
./UCGUI/Widget/RADIO_SetFont.o \
./UCGUI/Widget/RADIO_SetGroupId.o \
./UCGUI/Widget/RADIO_SetImage.o \
./UCGUI/Widget/RADIO_SetText.o \
./UCGUI/Widget/RADIO_SetTextColor.o \
./UCGUI/Widget/SCROLLBAR.o \
./UCGUI/Widget/SCROLLBAR_Create.o \
./UCGUI/Widget/SCROLLBAR_CreateIndirect.o \
./UCGUI/Widget/SCROLLBAR_Defaults.o \
./UCGUI/Widget/SCROLLBAR_GetValue.o \
./UCGUI/Widget/SCROLLBAR_SetColor.o \
./UCGUI/Widget/SCROLLBAR_SetWidth.o \
./UCGUI/Widget/SLIDER.o \
./UCGUI/Widget/SLIDER_Create.o \
./UCGUI/Widget/SLIDER_CreateIndirect.o \
./UCGUI/Widget/SLIDER_Default.o \
./UCGUI/Widget/SLIDER_SetFocusColor.o \
./UCGUI/Widget/TEXT.o \
./UCGUI/Widget/TEXT_Create.o \
./UCGUI/Widget/TEXT_CreateIndirect.o \
./UCGUI/Widget/TEXT_Default.o \
./UCGUI/Widget/TEXT_SetBkColor.o \
./UCGUI/Widget/TEXT_SetFont.o \
./UCGUI/Widget/TEXT_SetText.o \
./UCGUI/Widget/TEXT_SetTextAlign.o \
./UCGUI/Widget/TEXT_SetTextColor.o \
./UCGUI/Widget/TEXT_SetWrapMode.o \
./UCGUI/Widget/WIDGET.o \
./UCGUI/Widget/WIDGET_Effect_3D.o \
./UCGUI/Widget/WIDGET_Effect_3D1L.o \
./UCGUI/Widget/WIDGET_Effect_3D2L.o \
./UCGUI/Widget/WIDGET_Effect_None.o \
./UCGUI/Widget/WIDGET_Effect_Simple.o \
./UCGUI/Widget/WIDGET_FillStringInRect.o \
./UCGUI/Widget/WIDGET_SetEffect.o \
./UCGUI/Widget/WIDGET_SetWidth.o \
./UCGUI/Widget/WINDOW.o \
./UCGUI/Widget/WINDOW_Default.o 

C_DEPS += \
./UCGUI/Widget/BUTTON.d \
./UCGUI/Widget/BUTTON_BMP.d \
./UCGUI/Widget/BUTTON_Bitmap.d \
./UCGUI/Widget/BUTTON_Create.d \
./UCGUI/Widget/BUTTON_CreateIndirect.d \
./UCGUI/Widget/BUTTON_Default.d \
./UCGUI/Widget/BUTTON_Get.d \
./UCGUI/Widget/BUTTON_GetBitmap.d \
./UCGUI/Widget/BUTTON_IsPressed.d \
./UCGUI/Widget/BUTTON_SelfDraw.d \
./UCGUI/Widget/BUTTON_SetFocusColor.d \
./UCGUI/Widget/BUTTON_SetTextAlign.d \
./UCGUI/Widget/BUTTON_StreamedBitmap.d \
./UCGUI/Widget/BUTTON__SetBitmapObj.d \
./UCGUI/Widget/CHECKBOX.d \
./UCGUI/Widget/CHECKBOX_Create.d \
./UCGUI/Widget/CHECKBOX_CreateIndirect.d \
./UCGUI/Widget/CHECKBOX_Default.d \
./UCGUI/Widget/CHECKBOX_GetState.d \
./UCGUI/Widget/CHECKBOX_GetText.d \
./UCGUI/Widget/CHECKBOX_Image.d \
./UCGUI/Widget/CHECKBOX_IsChecked.d \
./UCGUI/Widget/CHECKBOX_SetBkColor.d \
./UCGUI/Widget/CHECKBOX_SetBoxBkColor.d \
./UCGUI/Widget/CHECKBOX_SetDefaultImage.d \
./UCGUI/Widget/CHECKBOX_SetFocusColor.d \
./UCGUI/Widget/CHECKBOX_SetFont.d \
./UCGUI/Widget/CHECKBOX_SetImage.d \
./UCGUI/Widget/CHECKBOX_SetNumStates.d \
./UCGUI/Widget/CHECKBOX_SetSpacing.d \
./UCGUI/Widget/CHECKBOX_SetState.d \
./UCGUI/Widget/CHECKBOX_SetText.d \
./UCGUI/Widget/CHECKBOX_SetTextAlign.d \
./UCGUI/Widget/CHECKBOX_SetTextColor.d \
./UCGUI/Widget/DIALOG.d \
./UCGUI/Widget/DROPDOWN.d \
./UCGUI/Widget/DROPDOWN_AddString.d \
./UCGUI/Widget/DROPDOWN_Create.d \
./UCGUI/Widget/DROPDOWN_CreateIndirect.d \
./UCGUI/Widget/DROPDOWN_Default.d \
./UCGUI/Widget/DROPDOWN_DeleteItem.d \
./UCGUI/Widget/DROPDOWN_GetNumItems.d \
./UCGUI/Widget/DROPDOWN_InsertString.d \
./UCGUI/Widget/DROPDOWN_ItemSpacing.d \
./UCGUI/Widget/DROPDOWN_SetAutoScroll.d \
./UCGUI/Widget/DROPDOWN_SetBkColor.d \
./UCGUI/Widget/DROPDOWN_SetColor.d \
./UCGUI/Widget/DROPDOWN_SetFont.d \
./UCGUI/Widget/DROPDOWN_SetScrollbarColor.d \
./UCGUI/Widget/DROPDOWN_SetScrollbarWidth.d \
./UCGUI/Widget/DROPDOWN_SetTextAlign.d \
./UCGUI/Widget/DROPDOWN_SetTextColor.d \
./UCGUI/Widget/DROPDOWN_SetTextHeight.d \
./UCGUI/Widget/EDIT.d \
./UCGUI/Widget/EDITBin.d \
./UCGUI/Widget/EDITDec.d \
./UCGUI/Widget/EDITFloat.d \
./UCGUI/Widget/EDITHex.d \
./UCGUI/Widget/EDITUlong.d \
./UCGUI/Widget/EDIT_Create.d \
./UCGUI/Widget/EDIT_CreateIndirect.d \
./UCGUI/Widget/EDIT_Default.d \
./UCGUI/Widget/EDIT_GetCursorPixelPos.d \
./UCGUI/Widget/EDIT_GetCursorPos.d \
./UCGUI/Widget/EDIT_GetNumChars.d \
./UCGUI/Widget/EDIT_SetCursorAtChar.d \
./UCGUI/Widget/EDIT_SetFocussable.d \
./UCGUI/Widget/EDIT_SetInsertMode.d \
./UCGUI/Widget/EDIT_SetSel.d \
./UCGUI/Widget/EDIT_SetTextMode.d \
./UCGUI/Widget/EDIT_SetpfAddKeyEx.d \
./UCGUI/Widget/EDIT_SetpfUpdateBuffer.d \
./UCGUI/Widget/FRAMEWIN.d \
./UCGUI/Widget/FRAMEWIN_AddMenu.d \
./UCGUI/Widget/FRAMEWIN_Button.d \
./UCGUI/Widget/FRAMEWIN_ButtonClose.d \
./UCGUI/Widget/FRAMEWIN_ButtonMax.d \
./UCGUI/Widget/FRAMEWIN_ButtonMin.d \
./UCGUI/Widget/FRAMEWIN_Create.d \
./UCGUI/Widget/FRAMEWIN_CreateIndirect.d \
./UCGUI/Widget/FRAMEWIN_Default.d \
./UCGUI/Widget/FRAMEWIN_Get.d \
./UCGUI/Widget/FRAMEWIN_IsMinMax.d \
./UCGUI/Widget/FRAMEWIN_MinMaxRest.d \
./UCGUI/Widget/FRAMEWIN_SetBorderSize.d \
./UCGUI/Widget/FRAMEWIN_SetColors.d \
./UCGUI/Widget/FRAMEWIN_SetFont.d \
./UCGUI/Widget/FRAMEWIN_SetResizeable.d \
./UCGUI/Widget/FRAMEWIN_SetTitleHeight.d \
./UCGUI/Widget/FRAMEWIN_SetTitleVis.d \
./UCGUI/Widget/FRAMEWIN__UpdateButtons.d \
./UCGUI/Widget/GRAPH.d \
./UCGUI/Widget/GRAPH_CreateIndirect.d \
./UCGUI/Widget/GRAPH_DATA_XY.d \
./UCGUI/Widget/GRAPH_DATA_YT.d \
./UCGUI/Widget/GRAPH_SCALE.d \
./UCGUI/Widget/GUI_ARRAY.d \
./UCGUI/Widget/GUI_ARRAY_DeleteItem.d \
./UCGUI/Widget/GUI_ARRAY_InsertItem.d \
./UCGUI/Widget/GUI_ARRAY_ResizeItem.d \
./UCGUI/Widget/GUI_DRAW.d \
./UCGUI/Widget/GUI_DRAW_BITMAP.d \
./UCGUI/Widget/GUI_DRAW_BMP.d \
./UCGUI/Widget/GUI_DRAW_STREAMED.d \
./UCGUI/Widget/GUI_DRAW_Self.d \
./UCGUI/Widget/GUI_EditBin.d \
./UCGUI/Widget/GUI_EditDec.d \
./UCGUI/Widget/GUI_EditFloat.d \
./UCGUI/Widget/GUI_EditHex.d \
./UCGUI/Widget/GUI_EditString.d \
./UCGUI/Widget/GUI_HOOK.d \
./UCGUI/Widget/HEADER.d \
./UCGUI/Widget/HEADER_BMP.d \
./UCGUI/Widget/HEADER_Bitmap.d \
./UCGUI/Widget/HEADER_Create.d \
./UCGUI/Widget/HEADER_CreateIndirect.d \
./UCGUI/Widget/HEADER_GetSel.d \
./UCGUI/Widget/HEADER_SetDragLimit.d \
./UCGUI/Widget/HEADER_StreamedBitmap.d \
./UCGUI/Widget/HEADER__SetDrawObj.d \
./UCGUI/Widget/LISTBOX.d \
./UCGUI/Widget/LISTBOX_Create.d \
./UCGUI/Widget/LISTBOX_CreateIndirect.d \
./UCGUI/Widget/LISTBOX_Default.d \
./UCGUI/Widget/LISTBOX_DeleteItem.d \
./UCGUI/Widget/LISTBOX_Font.d \
./UCGUI/Widget/LISTBOX_GetItemText.d \
./UCGUI/Widget/LISTBOX_GetNumItems.d \
./UCGUI/Widget/LISTBOX_GetTextAlign.d \
./UCGUI/Widget/LISTBOX_InsertString.d \
./UCGUI/Widget/LISTBOX_ItemDisabled.d \
./UCGUI/Widget/LISTBOX_ItemSpacing.d \
./UCGUI/Widget/LISTBOX_MultiSel.d \
./UCGUI/Widget/LISTBOX_ScrollStep.d \
./UCGUI/Widget/LISTBOX_SetAutoScroll.d \
./UCGUI/Widget/LISTBOX_SetBkColor.d \
./UCGUI/Widget/LISTBOX_SetOwner.d \
./UCGUI/Widget/LISTBOX_SetOwnerDraw.d \
./UCGUI/Widget/LISTBOX_SetScrollbarColor.d \
./UCGUI/Widget/LISTBOX_SetScrollbarWidth.d \
./UCGUI/Widget/LISTBOX_SetString.d \
./UCGUI/Widget/LISTBOX_SetTextAlign.d \
./UCGUI/Widget/LISTBOX_SetTextColor.d \
./UCGUI/Widget/LISTVIEW.d \
./UCGUI/Widget/LISTVIEW_Create.d \
./UCGUI/Widget/LISTVIEW_CreateIndirect.d \
./UCGUI/Widget/LISTVIEW_Default.d \
./UCGUI/Widget/LISTVIEW_DeleteAllRows.d \
./UCGUI/Widget/LISTVIEW_DeleteColumn.d \
./UCGUI/Widget/LISTVIEW_DeleteRow.d \
./UCGUI/Widget/LISTVIEW_DisableRow.d \
./UCGUI/Widget/LISTVIEW_GetBkColor.d \
./UCGUI/Widget/LISTVIEW_GetFont.d \
./UCGUI/Widget/LISTVIEW_GetHeader.d \
./UCGUI/Widget/LISTVIEW_GetItemText.d \
./UCGUI/Widget/LISTVIEW_GetNumColumns.d \
./UCGUI/Widget/LISTVIEW_GetNumRows.d \
./UCGUI/Widget/LISTVIEW_GetSel.d \
./UCGUI/Widget/LISTVIEW_GetTextColor.d \
./UCGUI/Widget/LISTVIEW_InsertRow.d \
./UCGUI/Widget/LISTVIEW_SetAutoScroll.d \
./UCGUI/Widget/LISTVIEW_SetBkColor.d \
./UCGUI/Widget/LISTVIEW_SetColumnWidth.d \
./UCGUI/Widget/LISTVIEW_SetFont.d \
./UCGUI/Widget/LISTVIEW_SetGridVis.d \
./UCGUI/Widget/LISTVIEW_SetItemColor.d \
./UCGUI/Widget/LISTVIEW_SetItemText.d \
./UCGUI/Widget/LISTVIEW_SetLBorder.d \
./UCGUI/Widget/LISTVIEW_SetRBorder.d \
./UCGUI/Widget/LISTVIEW_SetRowHeight.d \
./UCGUI/Widget/LISTVIEW_SetSel.d \
./UCGUI/Widget/LISTVIEW_SetSort.d \
./UCGUI/Widget/LISTVIEW_SetTextAlign.d \
./UCGUI/Widget/LISTVIEW_SetTextColor.d \
./UCGUI/Widget/LISTVIEW_UserData.d \
./UCGUI/Widget/MENU.d \
./UCGUI/Widget/MENU_Attach.d \
./UCGUI/Widget/MENU_CreateIndirect.d \
./UCGUI/Widget/MENU_Default.d \
./UCGUI/Widget/MENU_DeleteItem.d \
./UCGUI/Widget/MENU_DisableItem.d \
./UCGUI/Widget/MENU_EnableItem.d \
./UCGUI/Widget/MENU_GetItem.d \
./UCGUI/Widget/MENU_GetItemText.d \
./UCGUI/Widget/MENU_GetNumItems.d \
./UCGUI/Widget/MENU_InsertItem.d \
./UCGUI/Widget/MENU_Popup.d \
./UCGUI/Widget/MENU_SetBkColor.d \
./UCGUI/Widget/MENU_SetBorderSize.d \
./UCGUI/Widget/MENU_SetFont.d \
./UCGUI/Widget/MENU_SetItem.d \
./UCGUI/Widget/MENU_SetTextColor.d \
./UCGUI/Widget/MENU__FindItem.d \
./UCGUI/Widget/MESSAGEBOX.d \
./UCGUI/Widget/MULTIEDIT.d \
./UCGUI/Widget/MULTIEDIT_Create.d \
./UCGUI/Widget/MULTIEDIT_CreateIndirect.d \
./UCGUI/Widget/MULTIPAGE.d \
./UCGUI/Widget/MULTIPAGE_Create.d \
./UCGUI/Widget/MULTIPAGE_CreateIndirect.d \
./UCGUI/Widget/MULTIPAGE_Default.d \
./UCGUI/Widget/PROGBAR.d \
./UCGUI/Widget/PROGBAR_Create.d \
./UCGUI/Widget/PROGBAR_CreateIndirect.d \
./UCGUI/Widget/PROGBAR_SetBarColor.d \
./UCGUI/Widget/PROGBAR_SetFont.d \
./UCGUI/Widget/PROGBAR_SetMinMax.d \
./UCGUI/Widget/PROGBAR_SetText.d \
./UCGUI/Widget/PROGBAR_SetTextAlign.d \
./UCGUI/Widget/PROGBAR_SetTextColor.d \
./UCGUI/Widget/PROGBAR_SetTextPos.d \
./UCGUI/Widget/RADIO.d \
./UCGUI/Widget/RADIO_Create.d \
./UCGUI/Widget/RADIO_CreateIndirect.d \
./UCGUI/Widget/RADIO_Default.d \
./UCGUI/Widget/RADIO_GetText.d \
./UCGUI/Widget/RADIO_Image.d \
./UCGUI/Widget/RADIO_SetBkColor.d \
./UCGUI/Widget/RADIO_SetDefaultImage.d \
./UCGUI/Widget/RADIO_SetFocusColor.d \
./UCGUI/Widget/RADIO_SetFont.d \
./UCGUI/Widget/RADIO_SetGroupId.d \
./UCGUI/Widget/RADIO_SetImage.d \
./UCGUI/Widget/RADIO_SetText.d \
./UCGUI/Widget/RADIO_SetTextColor.d \
./UCGUI/Widget/SCROLLBAR.d \
./UCGUI/Widget/SCROLLBAR_Create.d \
./UCGUI/Widget/SCROLLBAR_CreateIndirect.d \
./UCGUI/Widget/SCROLLBAR_Defaults.d \
./UCGUI/Widget/SCROLLBAR_GetValue.d \
./UCGUI/Widget/SCROLLBAR_SetColor.d \
./UCGUI/Widget/SCROLLBAR_SetWidth.d \
./UCGUI/Widget/SLIDER.d \
./UCGUI/Widget/SLIDER_Create.d \
./UCGUI/Widget/SLIDER_CreateIndirect.d \
./UCGUI/Widget/SLIDER_Default.d \
./UCGUI/Widget/SLIDER_SetFocusColor.d \
./UCGUI/Widget/TEXT.d \
./UCGUI/Widget/TEXT_Create.d \
./UCGUI/Widget/TEXT_CreateIndirect.d \
./UCGUI/Widget/TEXT_Default.d \
./UCGUI/Widget/TEXT_SetBkColor.d \
./UCGUI/Widget/TEXT_SetFont.d \
./UCGUI/Widget/TEXT_SetText.d \
./UCGUI/Widget/TEXT_SetTextAlign.d \
./UCGUI/Widget/TEXT_SetTextColor.d \
./UCGUI/Widget/TEXT_SetWrapMode.d \
./UCGUI/Widget/WIDGET.d \
./UCGUI/Widget/WIDGET_Effect_3D.d \
./UCGUI/Widget/WIDGET_Effect_3D1L.d \
./UCGUI/Widget/WIDGET_Effect_3D2L.d \
./UCGUI/Widget/WIDGET_Effect_None.d \
./UCGUI/Widget/WIDGET_Effect_Simple.d \
./UCGUI/Widget/WIDGET_FillStringInRect.d \
./UCGUI/Widget/WIDGET_SetEffect.d \
./UCGUI/Widget/WIDGET_SetWidth.d \
./UCGUI/Widget/WINDOW.d \
./UCGUI/Widget/WINDOW_Default.d 


# Each subdirectory must supply rules for building sources it contributes
UCGUI/Widget/%.o: ../UCGUI/Widget/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m3 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DUSE_FULL_ASSERT -DSTM32F10X_CL -DUSE_STDPERIPH_DRIVER -DHSE_VALUE=8000000 -D__STDC_HOSTED__=1 -I"../system/include" -I"../system/include/cmsis" -I"../system/include/stm32f1-stdperiph" -I"/home/wty/arm_base/temp/UCGUI/Config" -I"/home/wty/arm_base/temp/UCGUI/Core" -I"/home/wty/arm_base/temp/UCGUI/JPEG" -I"/home/wty/arm_base/temp/UCGUI/MultiLayer" -I"/home/wty/arm_base/temp/UCGUI/Widget" -I"/home/wty/arm_base/temp/UCGUI/WM" -I../include -I"/home/wty/arm_base/temp/system/include/diag" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


