################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../UCGUI/Core/GUI2DLib.c \
../UCGUI/Core/GUIAlloc.c \
../UCGUI/Core/GUIArc.c \
../UCGUI/Core/GUIChar.c \
../UCGUI/Core/GUICharLine.c \
../UCGUI/Core/GUICharM.c \
../UCGUI/Core/GUICharP.c \
../UCGUI/Core/GUICirc.c \
../UCGUI/Core/GUIColor2Index.c \
../UCGUI/Core/GUICore.c \
../UCGUI/Core/GUICurs.c \
../UCGUI/Core/GUIEncJS.c \
../UCGUI/Core/GUIIndex2Color.c \
../UCGUI/Core/GUIPolyE.c \
../UCGUI/Core/GUIPolyM.c \
../UCGUI/Core/GUIPolyR.c \
../UCGUI/Core/GUIRealloc.c \
../UCGUI/Core/GUIStream.c \
../UCGUI/Core/GUITask.c \
../UCGUI/Core/GUITime.c \
../UCGUI/Core/GUITimer.c \
../UCGUI/Core/GUIUC0.c \
../UCGUI/Core/GUIVal.c \
../UCGUI/Core/GUIValf.c \
../UCGUI/Core/GUI_ALLOC_AllocInit.c \
../UCGUI/Core/GUI_ALLOC_AllocZero.c \
../UCGUI/Core/GUI_AddBin.c \
../UCGUI/Core/GUI_AddDec.c \
../UCGUI/Core/GUI_AddDecMin.c \
../UCGUI/Core/GUI_AddDecShift.c \
../UCGUI/Core/GUI_AddHex.c \
../UCGUI/Core/GUI_AddKeyMsgHook.c \
../UCGUI/Core/GUI_BMP.c \
../UCGUI/Core/GUI_BMP_Serialize.c \
../UCGUI/Core/GUI_CalcColorDist.c \
../UCGUI/Core/GUI_ClearRectEx.c \
../UCGUI/Core/GUI_Color2VisColor.c \
../UCGUI/Core/GUI_CursorArrowL.c \
../UCGUI/Core/GUI_CursorArrowLI.c \
../UCGUI/Core/GUI_CursorArrowLPx.c \
../UCGUI/Core/GUI_CursorArrowM.c \
../UCGUI/Core/GUI_CursorArrowMI.c \
../UCGUI/Core/GUI_CursorArrowMPx.c \
../UCGUI/Core/GUI_CursorArrowS.c \
../UCGUI/Core/GUI_CursorArrowSI.c \
../UCGUI/Core/GUI_CursorArrowSPx.c \
../UCGUI/Core/GUI_CursorCrossL.c \
../UCGUI/Core/GUI_CursorCrossLI.c \
../UCGUI/Core/GUI_CursorCrossLPx.c \
../UCGUI/Core/GUI_CursorCrossM.c \
../UCGUI/Core/GUI_CursorCrossMI.c \
../UCGUI/Core/GUI_CursorCrossMPx.c \
../UCGUI/Core/GUI_CursorCrossS.c \
../UCGUI/Core/GUI_CursorCrossSI.c \
../UCGUI/Core/GUI_CursorCrossSPx.c \
../UCGUI/Core/GUI_CursorHeaderM.c \
../UCGUI/Core/GUI_CursorHeaderMI.c \
../UCGUI/Core/GUI_CursorHeaderMPx.c \
../UCGUI/Core/GUI_CursorPal.c \
../UCGUI/Core/GUI_CursorPalI.c \
../UCGUI/Core/GUI_DispBin.c \
../UCGUI/Core/GUI_DispCEOL.c \
../UCGUI/Core/GUI_DispChar.c \
../UCGUI/Core/GUI_DispChars.c \
../UCGUI/Core/GUI_DispHex.c \
../UCGUI/Core/GUI_DispString.c \
../UCGUI/Core/GUI_DispStringAt.c \
../UCGUI/Core/GUI_DispStringAtCEOL.c \
../UCGUI/Core/GUI_DispStringHCenter.c \
../UCGUI/Core/GUI_DispStringInRect.c \
../UCGUI/Core/GUI_DispStringInRectEx.c \
../UCGUI/Core/GUI_DispStringInRectWrap.c \
../UCGUI/Core/GUI_DispStringLen.c \
../UCGUI/Core/GUI_DrawBitmap.c \
../UCGUI/Core/GUI_DrawBitmapEx.c \
../UCGUI/Core/GUI_DrawBitmapExp.c \
../UCGUI/Core/GUI_DrawBitmapMag.c \
../UCGUI/Core/GUI_DrawBitmap_555.c \
../UCGUI/Core/GUI_DrawBitmap_565.c \
../UCGUI/Core/GUI_DrawBitmap_888.c \
../UCGUI/Core/GUI_DrawFocusRect.c \
../UCGUI/Core/GUI_DrawGraph.c \
../UCGUI/Core/GUI_DrawGraphEx.c \
../UCGUI/Core/GUI_DrawHLine.c \
../UCGUI/Core/GUI_DrawLine.c \
../UCGUI/Core/GUI_DrawPie.c \
../UCGUI/Core/GUI_DrawPixel.c \
../UCGUI/Core/GUI_DrawPoint.c \
../UCGUI/Core/GUI_DrawPolygon.c \
../UCGUI/Core/GUI_DrawPolyline.c \
../UCGUI/Core/GUI_DrawRectEx.c \
../UCGUI/Core/GUI_DrawVLine.c \
../UCGUI/Core/GUI_ErrorOut.c \
../UCGUI/Core/GUI_Exec.c \
../UCGUI/Core/GUI_FillPolygon.c \
../UCGUI/Core/GUI_FillRect.c \
../UCGUI/Core/GUI_FillRectEx.c \
../UCGUI/Core/GUI_GIF.c \
../UCGUI/Core/GUI_GetBitmapPixelColor.c \
../UCGUI/Core/GUI_GetBitmapPixelIndex.c \
../UCGUI/Core/GUI_GetClientRect.c \
../UCGUI/Core/GUI_GetColor.c \
../UCGUI/Core/GUI_GetDispPos.c \
../UCGUI/Core/GUI_GetDrawMode.c \
../UCGUI/Core/GUI_GetFont.c \
../UCGUI/Core/GUI_GetFontInfo.c \
../UCGUI/Core/GUI_GetFontSizeY.c \
../UCGUI/Core/GUI_GetLineStyle.c \
../UCGUI/Core/GUI_GetOrg.c \
../UCGUI/Core/GUI_GetStringDistX.c \
../UCGUI/Core/GUI_GetTextAlign.c \
../UCGUI/Core/GUI_GetTextExtend.c \
../UCGUI/Core/GUI_GetTextMode.c \
../UCGUI/Core/GUI_GetVersionString.c \
../UCGUI/Core/GUI_GetYSizeOfFont.c \
../UCGUI/Core/GUI_Goto.c \
../UCGUI/Core/GUI_InitLUT.c \
../UCGUI/Core/GUI_InvertRect.c \
../UCGUI/Core/GUI_IsInFont.c \
../UCGUI/Core/GUI_Log.c \
../UCGUI/Core/GUI_MOUSE.c \
../UCGUI/Core/GUI_MOUSE_DriverPS2.c \
../UCGUI/Core/GUI_MergeRect.c \
../UCGUI/Core/GUI_MoveRect.c \
../UCGUI/Core/GUI_OnKey.c \
../UCGUI/Core/GUI_PID.c \
../UCGUI/Core/GUI_Pen.c \
../UCGUI/Core/GUI_RectsIntersect.c \
../UCGUI/Core/GUI_SIF.c \
../UCGUI/Core/GUI_SIF_Prop.c \
../UCGUI/Core/GUI_SaveContext.c \
../UCGUI/Core/GUI_ScreenSize.c \
../UCGUI/Core/GUI_SelectLCD.c \
../UCGUI/Core/GUI_SelectLayer.c \
../UCGUI/Core/GUI_SetClipRect.c \
../UCGUI/Core/GUI_SetColor.c \
../UCGUI/Core/GUI_SetColorIndex.c \
../UCGUI/Core/GUI_SetDecChar.c \
../UCGUI/Core/GUI_SetDefault.c \
../UCGUI/Core/GUI_SetDrawMode.c \
../UCGUI/Core/GUI_SetFont.c \
../UCGUI/Core/GUI_SetLBorder.c \
../UCGUI/Core/GUI_SetLUTColor.c \
../UCGUI/Core/GUI_SetLUTColorEx.c \
../UCGUI/Core/GUI_SetLUTEntry.c \
../UCGUI/Core/GUI_SetLineStyle.c \
../UCGUI/Core/GUI_SetOrg.c \
../UCGUI/Core/GUI_SetPixelIndex.c \
../UCGUI/Core/GUI_SetTextAlign.c \
../UCGUI/Core/GUI_SetTextMode.c \
../UCGUI/Core/GUI_SetTextStyle.c \
../UCGUI/Core/GUI_TOUCH.c \
../UCGUI/Core/GUI_TOUCH_DriverAnalog.c \
../UCGUI/Core/GUI_TOUCH_StoreState.c \
../UCGUI/Core/GUI_TOUCH_StoreUnstable.c \
../UCGUI/Core/GUI_UC.c \
../UCGUI/Core/GUI_UC_ConvertUC2UTF8.c \
../UCGUI/Core/GUI_UC_ConvertUTF82UC.c \
../UCGUI/Core/GUI_UC_DispString.c \
../UCGUI/Core/GUI_UC_EncodeNone.c \
../UCGUI/Core/GUI_UC_EncodeUTF8.c \
../UCGUI/Core/GUI_WaitEvent.c \
../UCGUI/Core/GUI_WaitKey.c \
../UCGUI/Core/GUI_Warn.c \
../UCGUI/Core/GUI__AddSpaceHex.c \
../UCGUI/Core/GUI__Arabic.c \
../UCGUI/Core/GUI__CalcTextRect.c \
../UCGUI/Core/GUI__DivideRound.c \
../UCGUI/Core/GUI__DivideRound32.c \
../UCGUI/Core/GUI__DrawBitmap16bpp.c \
../UCGUI/Core/GUI__GetCursorPos.c \
../UCGUI/Core/GUI__GetFontSizeY.c \
../UCGUI/Core/GUI__GetNumChars.c \
../UCGUI/Core/GUI__HandleEOLine.c \
../UCGUI/Core/GUI__IntersectRect.c \
../UCGUI/Core/GUI__IntersectRects.c \
../UCGUI/Core/GUI__Read.c \
../UCGUI/Core/GUI__ReduceRect.c \
../UCGUI/Core/GUI__SetText.c \
../UCGUI/Core/GUI__Wrap.c \
../UCGUI/Core/GUI__memset.c \
../UCGUI/Core/GUI__memset16.c \
../UCGUI/Core/GUI__strcmp.c \
../UCGUI/Core/GUI__strlen.c \
../UCGUI/Core/LCD.c \
../UCGUI/Core/LCDAA.c \
../UCGUI/Core/LCDColor.c \
../UCGUI/Core/LCDGetP.c \
../UCGUI/Core/LCDInfo.c \
../UCGUI/Core/LCDInfo0.c \
../UCGUI/Core/LCDInfo1.c \
../UCGUI/Core/LCDL0Delta.c \
../UCGUI/Core/LCDL0Mag.c \
../UCGUI/Core/LCDP1.c \
../UCGUI/Core/LCDP565_Index2Color.c \
../UCGUI/Core/LCDP888_Index2Color.c \
../UCGUI/Core/LCDPM565_Index2Color.c \
../UCGUI/Core/LCDPM888_Index2Color.c \
../UCGUI/Core/LCDRLE16.c \
../UCGUI/Core/LCDRLE4.c \
../UCGUI/Core/LCDRLE8.c \
../UCGUI/Core/LCD_API.c \
../UCGUI/Core/LCD_DrawVLine.c \
../UCGUI/Core/LCD_GetColorIndex.c \
../UCGUI/Core/LCD_GetEx.c \
../UCGUI/Core/LCD_GetNumDisplays.c \
../UCGUI/Core/LCD_GetPixelColor.c \
../UCGUI/Core/LCD_Index2ColorEx.c \
../UCGUI/Core/LCD_L0_Generic.c \
../UCGUI/Core/LCD_Mirror.c \
../UCGUI/Core/LCD_MixColors256.c \
../UCGUI/Core/LCD_ReadRect.c \
../UCGUI/Core/LCD_Rotate180.c \
../UCGUI/Core/LCD_RotateCCW.c \
../UCGUI/Core/LCD_RotateCW.c \
../UCGUI/Core/LCD_SelectLCD.c \
../UCGUI/Core/LCD_SetAPI.c \
../UCGUI/Core/LCD_SetClipRectEx.c \
../UCGUI/Core/LCD_UpdateColorIndices.c 

OBJS += \
./UCGUI/Core/GUI2DLib.o \
./UCGUI/Core/GUIAlloc.o \
./UCGUI/Core/GUIArc.o \
./UCGUI/Core/GUIChar.o \
./UCGUI/Core/GUICharLine.o \
./UCGUI/Core/GUICharM.o \
./UCGUI/Core/GUICharP.o \
./UCGUI/Core/GUICirc.o \
./UCGUI/Core/GUIColor2Index.o \
./UCGUI/Core/GUICore.o \
./UCGUI/Core/GUICurs.o \
./UCGUI/Core/GUIEncJS.o \
./UCGUI/Core/GUIIndex2Color.o \
./UCGUI/Core/GUIPolyE.o \
./UCGUI/Core/GUIPolyM.o \
./UCGUI/Core/GUIPolyR.o \
./UCGUI/Core/GUIRealloc.o \
./UCGUI/Core/GUIStream.o \
./UCGUI/Core/GUITask.o \
./UCGUI/Core/GUITime.o \
./UCGUI/Core/GUITimer.o \
./UCGUI/Core/GUIUC0.o \
./UCGUI/Core/GUIVal.o \
./UCGUI/Core/GUIValf.o \
./UCGUI/Core/GUI_ALLOC_AllocInit.o \
./UCGUI/Core/GUI_ALLOC_AllocZero.o \
./UCGUI/Core/GUI_AddBin.o \
./UCGUI/Core/GUI_AddDec.o \
./UCGUI/Core/GUI_AddDecMin.o \
./UCGUI/Core/GUI_AddDecShift.o \
./UCGUI/Core/GUI_AddHex.o \
./UCGUI/Core/GUI_AddKeyMsgHook.o \
./UCGUI/Core/GUI_BMP.o \
./UCGUI/Core/GUI_BMP_Serialize.o \
./UCGUI/Core/GUI_CalcColorDist.o \
./UCGUI/Core/GUI_ClearRectEx.o \
./UCGUI/Core/GUI_Color2VisColor.o \
./UCGUI/Core/GUI_CursorArrowL.o \
./UCGUI/Core/GUI_CursorArrowLI.o \
./UCGUI/Core/GUI_CursorArrowLPx.o \
./UCGUI/Core/GUI_CursorArrowM.o \
./UCGUI/Core/GUI_CursorArrowMI.o \
./UCGUI/Core/GUI_CursorArrowMPx.o \
./UCGUI/Core/GUI_CursorArrowS.o \
./UCGUI/Core/GUI_CursorArrowSI.o \
./UCGUI/Core/GUI_CursorArrowSPx.o \
./UCGUI/Core/GUI_CursorCrossL.o \
./UCGUI/Core/GUI_CursorCrossLI.o \
./UCGUI/Core/GUI_CursorCrossLPx.o \
./UCGUI/Core/GUI_CursorCrossM.o \
./UCGUI/Core/GUI_CursorCrossMI.o \
./UCGUI/Core/GUI_CursorCrossMPx.o \
./UCGUI/Core/GUI_CursorCrossS.o \
./UCGUI/Core/GUI_CursorCrossSI.o \
./UCGUI/Core/GUI_CursorCrossSPx.o \
./UCGUI/Core/GUI_CursorHeaderM.o \
./UCGUI/Core/GUI_CursorHeaderMI.o \
./UCGUI/Core/GUI_CursorHeaderMPx.o \
./UCGUI/Core/GUI_CursorPal.o \
./UCGUI/Core/GUI_CursorPalI.o \
./UCGUI/Core/GUI_DispBin.o \
./UCGUI/Core/GUI_DispCEOL.o \
./UCGUI/Core/GUI_DispChar.o \
./UCGUI/Core/GUI_DispChars.o \
./UCGUI/Core/GUI_DispHex.o \
./UCGUI/Core/GUI_DispString.o \
./UCGUI/Core/GUI_DispStringAt.o \
./UCGUI/Core/GUI_DispStringAtCEOL.o \
./UCGUI/Core/GUI_DispStringHCenter.o \
./UCGUI/Core/GUI_DispStringInRect.o \
./UCGUI/Core/GUI_DispStringInRectEx.o \
./UCGUI/Core/GUI_DispStringInRectWrap.o \
./UCGUI/Core/GUI_DispStringLen.o \
./UCGUI/Core/GUI_DrawBitmap.o \
./UCGUI/Core/GUI_DrawBitmapEx.o \
./UCGUI/Core/GUI_DrawBitmapExp.o \
./UCGUI/Core/GUI_DrawBitmapMag.o \
./UCGUI/Core/GUI_DrawBitmap_555.o \
./UCGUI/Core/GUI_DrawBitmap_565.o \
./UCGUI/Core/GUI_DrawBitmap_888.o \
./UCGUI/Core/GUI_DrawFocusRect.o \
./UCGUI/Core/GUI_DrawGraph.o \
./UCGUI/Core/GUI_DrawGraphEx.o \
./UCGUI/Core/GUI_DrawHLine.o \
./UCGUI/Core/GUI_DrawLine.o \
./UCGUI/Core/GUI_DrawPie.o \
./UCGUI/Core/GUI_DrawPixel.o \
./UCGUI/Core/GUI_DrawPoint.o \
./UCGUI/Core/GUI_DrawPolygon.o \
./UCGUI/Core/GUI_DrawPolyline.o \
./UCGUI/Core/GUI_DrawRectEx.o \
./UCGUI/Core/GUI_DrawVLine.o \
./UCGUI/Core/GUI_ErrorOut.o \
./UCGUI/Core/GUI_Exec.o \
./UCGUI/Core/GUI_FillPolygon.o \
./UCGUI/Core/GUI_FillRect.o \
./UCGUI/Core/GUI_FillRectEx.o \
./UCGUI/Core/GUI_GIF.o \
./UCGUI/Core/GUI_GetBitmapPixelColor.o \
./UCGUI/Core/GUI_GetBitmapPixelIndex.o \
./UCGUI/Core/GUI_GetClientRect.o \
./UCGUI/Core/GUI_GetColor.o \
./UCGUI/Core/GUI_GetDispPos.o \
./UCGUI/Core/GUI_GetDrawMode.o \
./UCGUI/Core/GUI_GetFont.o \
./UCGUI/Core/GUI_GetFontInfo.o \
./UCGUI/Core/GUI_GetFontSizeY.o \
./UCGUI/Core/GUI_GetLineStyle.o \
./UCGUI/Core/GUI_GetOrg.o \
./UCGUI/Core/GUI_GetStringDistX.o \
./UCGUI/Core/GUI_GetTextAlign.o \
./UCGUI/Core/GUI_GetTextExtend.o \
./UCGUI/Core/GUI_GetTextMode.o \
./UCGUI/Core/GUI_GetVersionString.o \
./UCGUI/Core/GUI_GetYSizeOfFont.o \
./UCGUI/Core/GUI_Goto.o \
./UCGUI/Core/GUI_InitLUT.o \
./UCGUI/Core/GUI_InvertRect.o \
./UCGUI/Core/GUI_IsInFont.o \
./UCGUI/Core/GUI_Log.o \
./UCGUI/Core/GUI_MOUSE.o \
./UCGUI/Core/GUI_MOUSE_DriverPS2.o \
./UCGUI/Core/GUI_MergeRect.o \
./UCGUI/Core/GUI_MoveRect.o \
./UCGUI/Core/GUI_OnKey.o \
./UCGUI/Core/GUI_PID.o \
./UCGUI/Core/GUI_Pen.o \
./UCGUI/Core/GUI_RectsIntersect.o \
./UCGUI/Core/GUI_SIF.o \
./UCGUI/Core/GUI_SIF_Prop.o \
./UCGUI/Core/GUI_SaveContext.o \
./UCGUI/Core/GUI_ScreenSize.o \
./UCGUI/Core/GUI_SelectLCD.o \
./UCGUI/Core/GUI_SelectLayer.o \
./UCGUI/Core/GUI_SetClipRect.o \
./UCGUI/Core/GUI_SetColor.o \
./UCGUI/Core/GUI_SetColorIndex.o \
./UCGUI/Core/GUI_SetDecChar.o \
./UCGUI/Core/GUI_SetDefault.o \
./UCGUI/Core/GUI_SetDrawMode.o \
./UCGUI/Core/GUI_SetFont.o \
./UCGUI/Core/GUI_SetLBorder.o \
./UCGUI/Core/GUI_SetLUTColor.o \
./UCGUI/Core/GUI_SetLUTColorEx.o \
./UCGUI/Core/GUI_SetLUTEntry.o \
./UCGUI/Core/GUI_SetLineStyle.o \
./UCGUI/Core/GUI_SetOrg.o \
./UCGUI/Core/GUI_SetPixelIndex.o \
./UCGUI/Core/GUI_SetTextAlign.o \
./UCGUI/Core/GUI_SetTextMode.o \
./UCGUI/Core/GUI_SetTextStyle.o \
./UCGUI/Core/GUI_TOUCH.o \
./UCGUI/Core/GUI_TOUCH_DriverAnalog.o \
./UCGUI/Core/GUI_TOUCH_StoreState.o \
./UCGUI/Core/GUI_TOUCH_StoreUnstable.o \
./UCGUI/Core/GUI_UC.o \
./UCGUI/Core/GUI_UC_ConvertUC2UTF8.o \
./UCGUI/Core/GUI_UC_ConvertUTF82UC.o \
./UCGUI/Core/GUI_UC_DispString.o \
./UCGUI/Core/GUI_UC_EncodeNone.o \
./UCGUI/Core/GUI_UC_EncodeUTF8.o \
./UCGUI/Core/GUI_WaitEvent.o \
./UCGUI/Core/GUI_WaitKey.o \
./UCGUI/Core/GUI_Warn.o \
./UCGUI/Core/GUI__AddSpaceHex.o \
./UCGUI/Core/GUI__Arabic.o \
./UCGUI/Core/GUI__CalcTextRect.o \
./UCGUI/Core/GUI__DivideRound.o \
./UCGUI/Core/GUI__DivideRound32.o \
./UCGUI/Core/GUI__DrawBitmap16bpp.o \
./UCGUI/Core/GUI__GetCursorPos.o \
./UCGUI/Core/GUI__GetFontSizeY.o \
./UCGUI/Core/GUI__GetNumChars.o \
./UCGUI/Core/GUI__HandleEOLine.o \
./UCGUI/Core/GUI__IntersectRect.o \
./UCGUI/Core/GUI__IntersectRects.o \
./UCGUI/Core/GUI__Read.o \
./UCGUI/Core/GUI__ReduceRect.o \
./UCGUI/Core/GUI__SetText.o \
./UCGUI/Core/GUI__Wrap.o \
./UCGUI/Core/GUI__memset.o \
./UCGUI/Core/GUI__memset16.o \
./UCGUI/Core/GUI__strcmp.o \
./UCGUI/Core/GUI__strlen.o \
./UCGUI/Core/LCD.o \
./UCGUI/Core/LCDAA.o \
./UCGUI/Core/LCDColor.o \
./UCGUI/Core/LCDGetP.o \
./UCGUI/Core/LCDInfo.o \
./UCGUI/Core/LCDInfo0.o \
./UCGUI/Core/LCDInfo1.o \
./UCGUI/Core/LCDL0Delta.o \
./UCGUI/Core/LCDL0Mag.o \
./UCGUI/Core/LCDP1.o \
./UCGUI/Core/LCDP565_Index2Color.o \
./UCGUI/Core/LCDP888_Index2Color.o \
./UCGUI/Core/LCDPM565_Index2Color.o \
./UCGUI/Core/LCDPM888_Index2Color.o \
./UCGUI/Core/LCDRLE16.o \
./UCGUI/Core/LCDRLE4.o \
./UCGUI/Core/LCDRLE8.o \
./UCGUI/Core/LCD_API.o \
./UCGUI/Core/LCD_DrawVLine.o \
./UCGUI/Core/LCD_GetColorIndex.o \
./UCGUI/Core/LCD_GetEx.o \
./UCGUI/Core/LCD_GetNumDisplays.o \
./UCGUI/Core/LCD_GetPixelColor.o \
./UCGUI/Core/LCD_Index2ColorEx.o \
./UCGUI/Core/LCD_L0_Generic.o \
./UCGUI/Core/LCD_Mirror.o \
./UCGUI/Core/LCD_MixColors256.o \
./UCGUI/Core/LCD_ReadRect.o \
./UCGUI/Core/LCD_Rotate180.o \
./UCGUI/Core/LCD_RotateCCW.o \
./UCGUI/Core/LCD_RotateCW.o \
./UCGUI/Core/LCD_SelectLCD.o \
./UCGUI/Core/LCD_SetAPI.o \
./UCGUI/Core/LCD_SetClipRectEx.o \
./UCGUI/Core/LCD_UpdateColorIndices.o 

C_DEPS += \
./UCGUI/Core/GUI2DLib.d \
./UCGUI/Core/GUIAlloc.d \
./UCGUI/Core/GUIArc.d \
./UCGUI/Core/GUIChar.d \
./UCGUI/Core/GUICharLine.d \
./UCGUI/Core/GUICharM.d \
./UCGUI/Core/GUICharP.d \
./UCGUI/Core/GUICirc.d \
./UCGUI/Core/GUIColor2Index.d \
./UCGUI/Core/GUICore.d \
./UCGUI/Core/GUICurs.d \
./UCGUI/Core/GUIEncJS.d \
./UCGUI/Core/GUIIndex2Color.d \
./UCGUI/Core/GUIPolyE.d \
./UCGUI/Core/GUIPolyM.d \
./UCGUI/Core/GUIPolyR.d \
./UCGUI/Core/GUIRealloc.d \
./UCGUI/Core/GUIStream.d \
./UCGUI/Core/GUITask.d \
./UCGUI/Core/GUITime.d \
./UCGUI/Core/GUITimer.d \
./UCGUI/Core/GUIUC0.d \
./UCGUI/Core/GUIVal.d \
./UCGUI/Core/GUIValf.d \
./UCGUI/Core/GUI_ALLOC_AllocInit.d \
./UCGUI/Core/GUI_ALLOC_AllocZero.d \
./UCGUI/Core/GUI_AddBin.d \
./UCGUI/Core/GUI_AddDec.d \
./UCGUI/Core/GUI_AddDecMin.d \
./UCGUI/Core/GUI_AddDecShift.d \
./UCGUI/Core/GUI_AddHex.d \
./UCGUI/Core/GUI_AddKeyMsgHook.d \
./UCGUI/Core/GUI_BMP.d \
./UCGUI/Core/GUI_BMP_Serialize.d \
./UCGUI/Core/GUI_CalcColorDist.d \
./UCGUI/Core/GUI_ClearRectEx.d \
./UCGUI/Core/GUI_Color2VisColor.d \
./UCGUI/Core/GUI_CursorArrowL.d \
./UCGUI/Core/GUI_CursorArrowLI.d \
./UCGUI/Core/GUI_CursorArrowLPx.d \
./UCGUI/Core/GUI_CursorArrowM.d \
./UCGUI/Core/GUI_CursorArrowMI.d \
./UCGUI/Core/GUI_CursorArrowMPx.d \
./UCGUI/Core/GUI_CursorArrowS.d \
./UCGUI/Core/GUI_CursorArrowSI.d \
./UCGUI/Core/GUI_CursorArrowSPx.d \
./UCGUI/Core/GUI_CursorCrossL.d \
./UCGUI/Core/GUI_CursorCrossLI.d \
./UCGUI/Core/GUI_CursorCrossLPx.d \
./UCGUI/Core/GUI_CursorCrossM.d \
./UCGUI/Core/GUI_CursorCrossMI.d \
./UCGUI/Core/GUI_CursorCrossMPx.d \
./UCGUI/Core/GUI_CursorCrossS.d \
./UCGUI/Core/GUI_CursorCrossSI.d \
./UCGUI/Core/GUI_CursorCrossSPx.d \
./UCGUI/Core/GUI_CursorHeaderM.d \
./UCGUI/Core/GUI_CursorHeaderMI.d \
./UCGUI/Core/GUI_CursorHeaderMPx.d \
./UCGUI/Core/GUI_CursorPal.d \
./UCGUI/Core/GUI_CursorPalI.d \
./UCGUI/Core/GUI_DispBin.d \
./UCGUI/Core/GUI_DispCEOL.d \
./UCGUI/Core/GUI_DispChar.d \
./UCGUI/Core/GUI_DispChars.d \
./UCGUI/Core/GUI_DispHex.d \
./UCGUI/Core/GUI_DispString.d \
./UCGUI/Core/GUI_DispStringAt.d \
./UCGUI/Core/GUI_DispStringAtCEOL.d \
./UCGUI/Core/GUI_DispStringHCenter.d \
./UCGUI/Core/GUI_DispStringInRect.d \
./UCGUI/Core/GUI_DispStringInRectEx.d \
./UCGUI/Core/GUI_DispStringInRectWrap.d \
./UCGUI/Core/GUI_DispStringLen.d \
./UCGUI/Core/GUI_DrawBitmap.d \
./UCGUI/Core/GUI_DrawBitmapEx.d \
./UCGUI/Core/GUI_DrawBitmapExp.d \
./UCGUI/Core/GUI_DrawBitmapMag.d \
./UCGUI/Core/GUI_DrawBitmap_555.d \
./UCGUI/Core/GUI_DrawBitmap_565.d \
./UCGUI/Core/GUI_DrawBitmap_888.d \
./UCGUI/Core/GUI_DrawFocusRect.d \
./UCGUI/Core/GUI_DrawGraph.d \
./UCGUI/Core/GUI_DrawGraphEx.d \
./UCGUI/Core/GUI_DrawHLine.d \
./UCGUI/Core/GUI_DrawLine.d \
./UCGUI/Core/GUI_DrawPie.d \
./UCGUI/Core/GUI_DrawPixel.d \
./UCGUI/Core/GUI_DrawPoint.d \
./UCGUI/Core/GUI_DrawPolygon.d \
./UCGUI/Core/GUI_DrawPolyline.d \
./UCGUI/Core/GUI_DrawRectEx.d \
./UCGUI/Core/GUI_DrawVLine.d \
./UCGUI/Core/GUI_ErrorOut.d \
./UCGUI/Core/GUI_Exec.d \
./UCGUI/Core/GUI_FillPolygon.d \
./UCGUI/Core/GUI_FillRect.d \
./UCGUI/Core/GUI_FillRectEx.d \
./UCGUI/Core/GUI_GIF.d \
./UCGUI/Core/GUI_GetBitmapPixelColor.d \
./UCGUI/Core/GUI_GetBitmapPixelIndex.d \
./UCGUI/Core/GUI_GetClientRect.d \
./UCGUI/Core/GUI_GetColor.d \
./UCGUI/Core/GUI_GetDispPos.d \
./UCGUI/Core/GUI_GetDrawMode.d \
./UCGUI/Core/GUI_GetFont.d \
./UCGUI/Core/GUI_GetFontInfo.d \
./UCGUI/Core/GUI_GetFontSizeY.d \
./UCGUI/Core/GUI_GetLineStyle.d \
./UCGUI/Core/GUI_GetOrg.d \
./UCGUI/Core/GUI_GetStringDistX.d \
./UCGUI/Core/GUI_GetTextAlign.d \
./UCGUI/Core/GUI_GetTextExtend.d \
./UCGUI/Core/GUI_GetTextMode.d \
./UCGUI/Core/GUI_GetVersionString.d \
./UCGUI/Core/GUI_GetYSizeOfFont.d \
./UCGUI/Core/GUI_Goto.d \
./UCGUI/Core/GUI_InitLUT.d \
./UCGUI/Core/GUI_InvertRect.d \
./UCGUI/Core/GUI_IsInFont.d \
./UCGUI/Core/GUI_Log.d \
./UCGUI/Core/GUI_MOUSE.d \
./UCGUI/Core/GUI_MOUSE_DriverPS2.d \
./UCGUI/Core/GUI_MergeRect.d \
./UCGUI/Core/GUI_MoveRect.d \
./UCGUI/Core/GUI_OnKey.d \
./UCGUI/Core/GUI_PID.d \
./UCGUI/Core/GUI_Pen.d \
./UCGUI/Core/GUI_RectsIntersect.d \
./UCGUI/Core/GUI_SIF.d \
./UCGUI/Core/GUI_SIF_Prop.d \
./UCGUI/Core/GUI_SaveContext.d \
./UCGUI/Core/GUI_ScreenSize.d \
./UCGUI/Core/GUI_SelectLCD.d \
./UCGUI/Core/GUI_SelectLayer.d \
./UCGUI/Core/GUI_SetClipRect.d \
./UCGUI/Core/GUI_SetColor.d \
./UCGUI/Core/GUI_SetColorIndex.d \
./UCGUI/Core/GUI_SetDecChar.d \
./UCGUI/Core/GUI_SetDefault.d \
./UCGUI/Core/GUI_SetDrawMode.d \
./UCGUI/Core/GUI_SetFont.d \
./UCGUI/Core/GUI_SetLBorder.d \
./UCGUI/Core/GUI_SetLUTColor.d \
./UCGUI/Core/GUI_SetLUTColorEx.d \
./UCGUI/Core/GUI_SetLUTEntry.d \
./UCGUI/Core/GUI_SetLineStyle.d \
./UCGUI/Core/GUI_SetOrg.d \
./UCGUI/Core/GUI_SetPixelIndex.d \
./UCGUI/Core/GUI_SetTextAlign.d \
./UCGUI/Core/GUI_SetTextMode.d \
./UCGUI/Core/GUI_SetTextStyle.d \
./UCGUI/Core/GUI_TOUCH.d \
./UCGUI/Core/GUI_TOUCH_DriverAnalog.d \
./UCGUI/Core/GUI_TOUCH_StoreState.d \
./UCGUI/Core/GUI_TOUCH_StoreUnstable.d \
./UCGUI/Core/GUI_UC.d \
./UCGUI/Core/GUI_UC_ConvertUC2UTF8.d \
./UCGUI/Core/GUI_UC_ConvertUTF82UC.d \
./UCGUI/Core/GUI_UC_DispString.d \
./UCGUI/Core/GUI_UC_EncodeNone.d \
./UCGUI/Core/GUI_UC_EncodeUTF8.d \
./UCGUI/Core/GUI_WaitEvent.d \
./UCGUI/Core/GUI_WaitKey.d \
./UCGUI/Core/GUI_Warn.d \
./UCGUI/Core/GUI__AddSpaceHex.d \
./UCGUI/Core/GUI__Arabic.d \
./UCGUI/Core/GUI__CalcTextRect.d \
./UCGUI/Core/GUI__DivideRound.d \
./UCGUI/Core/GUI__DivideRound32.d \
./UCGUI/Core/GUI__DrawBitmap16bpp.d \
./UCGUI/Core/GUI__GetCursorPos.d \
./UCGUI/Core/GUI__GetFontSizeY.d \
./UCGUI/Core/GUI__GetNumChars.d \
./UCGUI/Core/GUI__HandleEOLine.d \
./UCGUI/Core/GUI__IntersectRect.d \
./UCGUI/Core/GUI__IntersectRects.d \
./UCGUI/Core/GUI__Read.d \
./UCGUI/Core/GUI__ReduceRect.d \
./UCGUI/Core/GUI__SetText.d \
./UCGUI/Core/GUI__Wrap.d \
./UCGUI/Core/GUI__memset.d \
./UCGUI/Core/GUI__memset16.d \
./UCGUI/Core/GUI__strcmp.d \
./UCGUI/Core/GUI__strlen.d \
./UCGUI/Core/LCD.d \
./UCGUI/Core/LCDAA.d \
./UCGUI/Core/LCDColor.d \
./UCGUI/Core/LCDGetP.d \
./UCGUI/Core/LCDInfo.d \
./UCGUI/Core/LCDInfo0.d \
./UCGUI/Core/LCDInfo1.d \
./UCGUI/Core/LCDL0Delta.d \
./UCGUI/Core/LCDL0Mag.d \
./UCGUI/Core/LCDP1.d \
./UCGUI/Core/LCDP565_Index2Color.d \
./UCGUI/Core/LCDP888_Index2Color.d \
./UCGUI/Core/LCDPM565_Index2Color.d \
./UCGUI/Core/LCDPM888_Index2Color.d \
./UCGUI/Core/LCDRLE16.d \
./UCGUI/Core/LCDRLE4.d \
./UCGUI/Core/LCDRLE8.d \
./UCGUI/Core/LCD_API.d \
./UCGUI/Core/LCD_DrawVLine.d \
./UCGUI/Core/LCD_GetColorIndex.d \
./UCGUI/Core/LCD_GetEx.d \
./UCGUI/Core/LCD_GetNumDisplays.d \
./UCGUI/Core/LCD_GetPixelColor.d \
./UCGUI/Core/LCD_Index2ColorEx.d \
./UCGUI/Core/LCD_L0_Generic.d \
./UCGUI/Core/LCD_Mirror.d \
./UCGUI/Core/LCD_MixColors256.d \
./UCGUI/Core/LCD_ReadRect.d \
./UCGUI/Core/LCD_Rotate180.d \
./UCGUI/Core/LCD_RotateCCW.d \
./UCGUI/Core/LCD_RotateCW.d \
./UCGUI/Core/LCD_SelectLCD.d \
./UCGUI/Core/LCD_SetAPI.d \
./UCGUI/Core/LCD_SetClipRectEx.d \
./UCGUI/Core/LCD_UpdateColorIndices.d 


# Each subdirectory must supply rules for building sources it contributes
UCGUI/Core/%.o: ../UCGUI/Core/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m3 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DUSE_FULL_ASSERT -DSTM32F10X_CL -DUSE_STDPERIPH_DRIVER -DHSE_VALUE=8000000 -D__STDC_HOSTED__=1 -I"../system/include" -I"../system/include/cmsis" -I"../system/include/stm32f1-stdperiph" -I"/home/wty/arm_base/temp/UCGUI/Config" -I"/home/wty/arm_base/temp/UCGUI/Core" -I"/home/wty/arm_base/temp/UCGUI/JPEG" -I"/home/wty/arm_base/temp/UCGUI/MultiLayer" -I"/home/wty/arm_base/temp/UCGUI/Widget" -I"/home/wty/arm_base/temp/UCGUI/WM" -I../include -I"/home/wty/arm_base/temp/system/include/diag" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


